config/routes.rb
UcsXc::Application.routes.draw do
  devise_for :users
  root to: 'songs#index'
  resources :songs
  resources :steps do
    get 'download'
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :steps

  validates_presence_of :title, :artist, :bpm, :ucs_id
  validates_uniqueness_of :ucs_id
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :user
  belongs_to :song

  mount_uploader :attachment, AttachmentUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :steps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/concerns/gfx_lists.rb
module GfxLists
  extend ActiveSupport::Concern

  included do
    before_action :get_headers
  end

  private

  def get_headers
    @headers = Array.new
    Dir.foreach('app/assets/images/headers/') {|x| @headers << x unless (x=="."||x=="..")}
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  include GfxLists
  expose :song, attributes: :song_params
  expose :songs

  def index
  end

  def show
  end

  def new
  end

  def create
    if song.save(song_params)
      flash[:notice] = 'Song has been created successfully.'
      redirect_to song_path song.id
    else
      flash[:error] = 'Something went wrong. Try again.'
      redirect_to new_song_path
    end
  end

  def edit
  end

  def update
    if song.update_attributes(song_params)
      flash[:notice] = 'Song has been edited successfully.'
      redirect_to song_path song.id
    else
      flash[:error] = 'Something went wrong. Try again.'
      redirect_to edit_song_path song.id
    end
  end

  def destroy
    if song.destroy
      flash[:notice] = 'Song has been destroyed sucessfully.'
      redirect_to songs_path
    else
      flash[:error] = 'Something went wrong. Try again.'
      redirect_to songs_path
    end
  end

  private

  def song_params
    params.require(:song).permit(:title,:artist,:bpm,:delay,:ucs_id)
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  include GfxLists
  expose(:step, attributes: :step_params)
  expose(:steps)
  expose(:songs)

  def index
  end

  def new
  end

  def create
    if step.save(step_params)
      flash[:notice] = 'Stepchart has been uploaded succesfully'
      redirect_to steps_path
    else
      flash[:error] = 'Stepchart was not uploaded'
      redirect_to new_step_path
    end
  end

  def edit
  end

  def update
    if step.save(step_params)
      flash[:notice] = 'Stepchart has been edited succesfully'
      redirect_to step_path(step.id)
    else
      flash[:error] = 'Stepchart was not updated'
      redirect_to edit_step_path(song_id)
    end
  end

  def destroy
    if step.destroy
      flash[:notice] = 'Stepchart has been deleted successfully'
      redirect_to steps_path
    else
      flash[:error] = 'Stepchart was not deleted'
      redirect_to steps_path
    end
  end

  def download
    file_to_download = "#{Rails.root}/public#{step.attachment_url}"
    send_file file_to_download
  end

  private

  def step_params
    params.require(:step).permit(:user_id, :song_id, :attachment, :video_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UCS Exchange Central</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'UCS Exchange Central', root_path %></h1>
      </li>
    </ul>
    <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to 'Songs', songs_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Steps', steps_path %></li>
    </ul>
    </section>
  </nav>

  <%= yield %>

</body>
</html>

app/views/songs/_form.html.haml
=form_for song do |f|      
  = f.label :title         
  = f.text_field :title    
  = f.label :artist        
  = f.text_field :artist   
  = f.label :bpm           
  = f.text_field :bpm      
  = f.label :delay         
  = f.text_field :delay    
  = f.label :ucs_id        
  = f.text_field :ucs_id   
  = f.submit

app/views/songs/edit.html.haml
%header{ style: "padding: 22px 0; background-image: url('..#{image_path('headers/' << @headers.sample)}');" }
  .row
    .large-12.columns
      %h1 Edit Song
      %h4 Amend song information
%section{ style: 'margin-top: 44px' }
  .row
    .large-8.columns
      = render 'form'

app/views/songs/index.html.haml
%header{ style: "padding: 22px 0; background-image: url('..#{image_path('headers/' << @headers.sample)}');" }
  .row
    .large-12.columns
      %h1 Songs
      %h4 Stepmakeable song list
%section{ style: 'margin-top: 44px' }
  .row
    .large-8.columns
      - songs.each do |song|
        .large-8.columns
          = song.title
          %span{ style: 'display: block; font-size: small;' }by #{song.artist}
        .large-4.columns
          .button-bar
            %ul{class: 'button-group round'}
              %li
                = link_to 'Edit', edit_song_path(song.id), class: 'tiny button secondary'
              %li
                = link_to 'Destroy', song_path(song.id), method: :delete, class: 'tiny button alert'
        %br
        %hr
      =link_to "Add song", new_song_path, class: 'button [radius round]'

app/views/songs/new.html.haml
%header{ style: "padding: 22px 0; background-image: url('..#{image_path('headers/' << @headers.sample)}');" }
  .row
    .large-12.columns
      %h1 Add Song
      %h4 Set song information
%section{ style: 'margin-top: 44px' }
  .row
    .large-8.columns
      = render 'form'

app/views/songs/show.html.haml
%h1= song.title
%h3= "by #{song.artist}"
%p= "BPM: #{song.bpm}"
%p= "Delay #{song.delay}"
%p= "UCS ID: #{song.ucs_id}"

app/views/steps/_form.html.haml
= form_for step, html: { multipart: true } do |f|
  = f.label :song_id, 'Song'
  = f.collection_select :song_id, songs, :id, :title
  %br
  = f.label :video_url, 'YouTube URL'
  = f.text_field :video_url
  %br
  = f.label :attachment, 'UCS File'
  = f.file_field :attachment
  %br
  = f.submit

app/views/steps/edit.html.haml
%h1 Edit stepchart
=render 'form'

app/views/steps/index.html.haml
%header{ style: "padding: 22px 0; background-image: url('..#{image_path('headers/' << @headers.sample)}');" }
  .row
    .large-12.columns
      %h1 Steps
      %h4 Explore our stepcharts library
%section{ style: 'margin-top: 44px' }
  .row
    .large-8.columns
      - steps.each do |step|
        = link_to step.song.title, step_path(step.id)
        = link_to 'UCS File', step_download_path(step.id), target: '_blank'
        = link_to 'Edit', edit_step_path(step.id)
        = link_to 'Destroy', step_path(step.id), method: :delete
    %br
    %hr
    =link_to "New stepchart", new_step_path

app/views/steps/new.html.haml
%h1 New stepchart
=render 'form'

app/views/steps/show.html.haml
%h1= step.song.title
=link_to 'YouTube Video', step.video_url
=link_to 'UCS File', step_download_path(step.id), target: '_blank'